sonar.projectKey=ProjetPiscine_EnerVision
sonar.organization=groupe3-ener-vision
sonar.sourceEncoding=UTF-8

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=apps/frontend/src

# Répertoire contenant les TU
sonar.tests=apps/frontend/src

sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.js,**/*.test.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=apps/frontend/coverage//frontend/lcov.info
