sonar.projectKey=ProjetPiscine_EnerVision
sonar.organization=groupe3-ener-vision
sonar.sourceEncoding=UTF-8

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=apps/frontend/src,apps/backend/src

# Répertoire contenant les TU
sonar.tests=apps/frontend/tests,apps/backend/tests,apps/frontend/tests/**,apps/backend/tests/**

sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.js,**/*.test.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.junit.reportPaths=apps/frontend/tests/test-results
