sonar.projectKey=ProjetPiscine_EnerVision
sonar.organization=groupe3-ener-vision
sonar.sourceEncoding=UTF-8

#  Dossier contenant le code source
sonar.sources=apps/frontend/src,apps/backend
#  Dossier contenant les tests
sonar.tests=apps/frontend/src,apps/backend/tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*test_*.py,**/*test.py

#  Liste des fichiers et dossiers à exclure de l'analyse
sonar.exclusions=.pytest_cache,.venv,alembic,tests,**/*/node_modules/**,**/*/dist/**,**/*/build/**,**/*.spec.ts,**/*.test.ts,**/*test_*.py,**/*test.py

#  Chemin vers le rapport de couverture de code
#  Fichier généré par Pytest
sonar.python.coverage.reportPaths=apps/backend/coverage.xml
sonar.javascript.lcov.reportPaths=apps/frontend/coverage/frontend/lcov.info
