sonar.projectKey=ProjetPiscine_EnerVision
sonar.organization=groupe3-ener-vision
sonar.sourceEncoding=UTF-8

#  Dossier contenant le code source
sonar.sources=app
#  Dossier contenant les tests
sonar.tests=tests

#  Liste des fichiers et dossiers à exclure de l'analyse
sonar.exclusions=.pytest_cache,.venv,alembic,tests

#  Chemin vers le rapport de couverture de code
#  Fichier généré par Pytest
sonar.python.coverage.reportPaths=cov.info
